import type { CharacterInput } from "@threepointpf/rules-schema";

/** Core sheet data transcribed from Main Sheet in the supplied Autosheet. */
export const charlieCharacter: CharacterInput = {
  id: "sample-charlie-runecarved-human",
  campaignId: "demo-campaign",
  name: "Charlie",
  baseAbilities: { str: 10, dex: 16, con: 18, int: 26, wis: 10, cha: 10 },
  // Three maximum d8 hit dice plus Constitution gives the workbook's 36 HP.
  baseHpBeforeConstitution: 24,
  baseLandSpeed: 30,
  baseSpeeds: { land: 30, fly: 0, swim: 0, climb: 0, burrow: 0 },
  baseSize: "medium",
  record: {
    alignment: "Neutral",
    race: "Runecarved Human",
    ageCategory: "Adult",
    traits: ["Bruising Intellect", "Unorthodox Method (Broken Blade → Black Seraph)"],
    feats: ["Extra Origin Feat (Uncanny Aptitude—Nodachi)", "Focused Veil (Dimensional Bridge)", "Hidden Brandweaver", "Extra Readied Maneuver"],
    racialFeatures: ["Domain Rune: Trickery", "Runic Complexity (Su)", "Runic Dominance"],
    classFeatures: ["Stalker Art (Rogue Talent: Prescient Dodger)", "Stalker Art (Rogue Talent: Shape Veil (Izanami's Nodachi))", "Soul Claiming", "Daayan Veilweaving", "Path of the Vazputrika", "Ruler's Domain", "Actions of a Ruler", "Strings of the Sun King", "Branded Vassal", "Empowered Brands", "Oppressing Presence", "Tyrant's Grasp"],
    story: { notes: "Daayan Rajah\nSoul Hunter Stalker\n\nDisguise Self (1st level) and Invisibility (2nd level) are spell-like abilities, each usable once per day. No separate caster-level source is recorded, so the spell-like ability default uses character level." },
  },
  advancementSlots: [1, 2, 3].map((level) => ({
    id: `charlie-level-${level}`,
    tracks: [
      { id: "charlie-rajah", entry: { progressionId: "pf1e.3pp.akashic.rajah" } },
      { id: "charlie-stalker", entry: { progressionId: "pf1e.dreamscarred-press.path-of-war.stalker" } },
    ],
  })),
  skillRanks: {
    acrobatics: 3,
    bluff: 3,
    diplomacy: 3,
    disguise: 3,
    "escape-artist": 3,
    intimidate: 3,
    "knowledge-arcana": 3,
    "knowledge-local": 3,
    "knowledge-nature": 3,
    "knowledge-religion": 3,
    perception: 3,
    spellcraft: 3,
    stealth: 3,
    swim: 3,
    // The workbook's separate Background Skills section.
    appraise: 3,
    linguistics: 3,
  },
  skills: {
    // Direct Main Sheet miscellaneous-column inputs, in addition to ranks,
    // ability modifiers, and class-skill bonuses.
    "knowledge-arcana": { miscellaneous: 8 },
    linguistics: { miscellaneous: 8 },
  },
  attacks: [
    {
      id: "izanamis-nodachi",
      name: "Izanami's Nodachi",
      attackAbility: "int",
      damageAbility: "int",
      baseDamage: { count: 1, sides: 10 },
      attackTags: ["weapon.melee", "weapon.two-handed"],
      mode: "melee",
      criticalRange: { minimumNaturalRoll: 18 },
      criticalMultiplier: 2,
    },
    {
      id: "izanamis-nodachi-soulburn",
      name: "Izanami's Nodachi (Soulburn)",
      attackAbility: "int",
      damageAbility: "int",
      baseDamage: { count: 1, sides: 10 },
      attackTags: ["weapon.melee", "weapon.two-handed"],
      mode: "melee",
      criticalRange: { minimumNaturalRoll: 18 },
      criticalMultiplier: 2,
    },
  ],
  features: [
    {
      id: "charlie-prescient-dodger",
      name: "Prescient Dodger",
      description: "Stalker art; the workbook formula is Intelligence modifier + floor(character level / 4).",
      enabled: true,
      effects: [{ kind: "modifier", target: "ac", value: 1, bonusType: "dodge", appliesTo: ["normal", "touch", "flatFooted"], scaling: { kind: "abilityLevelStep", ability: "int", every: 4, base: 0 } }],
    },
    {
      id: "charlie-nodachi-veil",
      name: "Izanami's Nodachi · Veil",
      description: "The workbook lists 2d4+1 bleed damage on this attack.",
      enabled: true,
      effects: [
        {
          kind: "modifier",
          target: "damage.melee",
          value: 1,
          bonusType: "untyped",
          damageType: "bleed",
          appliesWhen: { attackIds: ["izanamis-nodachi", "izanamis-nodachi-soulburn"] },
        },
        {
          kind: "damageDice",
          target: "damage.melee",
          dice: { count: 2, sides: 4 },
          damageType: "bleed",
          label: "Nodachi bleed",
          criticalBehavior: "notMultiplied",
          appliesWhen: { attackIds: ["izanamis-nodachi", "izanamis-nodachi-soulburn"] },
        },
      ],
    },
    {
      id: "charlie-soulburning",
      name: "Soulburning (Su)",
      description: "Optional +1d6 Soulburn damage from the workbook's Soulburn attack entry.",
      enabled: true,
      effects: [{
        kind: "damageDice",
        target: "damage.melee",
        dice: { count: 1, sides: 6 },
        damageType: "soulburn",
        label: "Soulburn",
        criticalBehavior: "normal",
        appliesWhen: { attackIds: ["izanamis-nodachi-soulburn"] },
      }],
    },
  ],
  abilities: [
    {
      id: "charlie-copycat",
      name: "Copycat (Sp)",
      description: "Move action: create one illusory double that functions as a single mirror image. It lasts a number of rounds equal to cleric level or until destroyed or dispelled. Only one copycat can exist at a time, and it does not stack with mirror image. The workbook records 11 uses per day. Charlie has no cleric level recorded, so track the duration manually.",
      activation: "activated",
      actionCost: "move",
      effects: [],
      spellLike: true,
      spellLikeFrequency: "custom",
      spellLikeCastingAbility: "cha",
      usesPerDay: 11,
      usesSpent: 0,
    },
    {
      id: "charlie-disguise-self-sla",
      name: "Disguise Self (Sp)",
      description: "Changes your apparent appearance for 10 minutes per caster level. The workbook marks this spell-like ability as usable once per day.",
      activation: "activated",
      effects: [],
      spellLike: true,
      spellLikeFrequency: "onePerDay",
      spellLikeSpellLevel: 1,
      spellLikeCastingAbility: "cha",
      spellId: "charlie.disguise-self",
      usesPerDay: 1,
      usesSpent: 0,
    },
    {
      id: "charlie-invisibility-sla",
      name: "Invisibility (Sp)",
      description: "Makes you invisible for 1 minute per caster level. The workbook marks this spell-like ability as usable once per day.",
      activation: "activated",
      effects: [],
      spellLike: true,
      spellLikeFrequency: "onePerDay",
      spellLikeSpellLevel: 2,
      spellLikeCastingAbility: "cha",
      spellId: "charlie.invisibility",
      usesPerDay: 1,
      usesSpent: 0,
    },
  ],
  customSpells: {
    "charlie.disguise-self": {
      id: "charlie.disguise-self",
      name: "Disguise Self",
      description: "Changes your apparent appearance, including clothing and carried equipment. It grants +10 on Disguise checks to create a disguise; a creature that interacts with the illusion can attempt a Will disbelief save.",
      school: "illusion",
      subschool: "glamer",
      levels: [{ spellListId: "spell-like.charlie", level: 1 }],
      castingTime: { action: "standard" },
      components: [],
      range: "personal",
      target: "you",
      duration: "10 minutes per caster level (dismissible)",
      source: { document: "Pathfinder Core Rulebook", sheet: "Spells", range: "Disguise Self", system: "PF1e", category: "Spell-like ability" },
    },
    "charlie.invisibility": {
      id: "charlie.invisibility",
      name: "Invisibility",
      description: "Makes you and your carried gear invisible. The effect ends when you attack.",
      school: "illusion",
      subschool: "glamer",
      levels: [{ spellListId: "spell-like.charlie", level: 2 }],
      castingTime: { action: "standard" },
      components: [],
      range: "personal",
      target: "you",
      duration: "1 minute per caster level (dismissible)",
      source: { document: "Pathfinder Core Rulebook", sheet: "Spells", range: "Invisibility", system: "PF1e", category: "Spell-like ability" },
    },
  },
  resources: [{
    id: "charlie-ki-pool",
    name: "Ki Pool",
    maximum: { kind: "manual", value: 11 },
    refresh: { kind: "rest" },
  }],
  resourceStates: [{ resourceId: "charlie-ki-pool", spent: 0 }],
  systems: [{
    id: "charlie-stalker-maneuvers",
    kind: "maneuvers",
    name: "Stalker Maneuvers & Stances",
    progressionId: "pf1e.dreamscarred-press.path-of-war.stalker",
    keyAbility: "int",
    resourceName: "Readied maneuvers",
    resourceSpent: 0,
    progression: [{ level: 3, casterLevel: 3, maximumTier: 2, knownByTier: { "1": 6, "2": 2 } }],
    notes: "Workbook: class level 3; Intelligence key ability (modifier +8); 1st-level maneuver DC 19 and 2nd-level maneuver DC 20. Readied selection is not marked in the workbook, so entries start un-readied.",
    entries: [
      { id: "charlie-stance-aura-misfortune", name: "Aura of Misfortune", category: "Stance", actionCost: "swift", known: true, description: "Cursed Razor 1: while maintained, opponents within close range take a −2 penalty on saving throws." },
      { id: "charlie-stance-black-seraph-glare", name: "Black Seraph's Glare", category: "Stance", actionCost: "swift", known: true },
      { id: "charlie-maneuver-woeful-burden", name: "Woeful Burden", category: "Strike · Cursed Razor", actionCost: "standard", tier: 1, known: true, readied: false, description: "On a hit, deal normal weapon damage, reduce each movement speed by 10 ft. + 5 ft. per four initiator levels, and curse the target for initiator-level rounds.", roll: { kind: "weaponAttack", attackId: "izanamis-nodachi" } },
      { id: "charlie-maneuver-strike-hourglass", name: "Strike The Hourglass", category: "Strike · Riven Hourglass", actionCost: "standard", tier: 1, known: true, readied: false, description: "Weapon strike; on a hit, the target may lose its next move action. The target's defense is resolved by the table's separate maneuver rules.", roll: { kind: "weaponAttack", attackId: "izanamis-nodachi" } },
      { id: "charlie-maneuver-strength-hell", name: "Strength of Hell", category: "Boost · Black Seraph", actionCost: "swift", tier: 1, known: true, readied: false, active: false, description: "Until the next turn: +2 profane on melee attack rolls, +1d6 damage, and −2 AC. Toggle off after its duration ends.", effects: [
        { kind: "modifier", target: "attack.melee", value: 2, bonusType: "profane", appliesWhen: { kinds: ["attack"], modes: ["melee"] } },
        { kind: "damageDice", target: "damage.melee", dice: { count: 1, sides: 6 }, damageType: "profane", label: "Strength of Hell", criticalBehavior: "normal", appliesWhen: { modes: ["melee"] } },
        { kind: "modifier", target: "ac", value: -2, bonusType: "untyped", appliesTo: ["normal", "touch", "flatFooted", "deniedDexterity"] },
      ] },
      { id: "charlie-maneuver-minute-hand", name: "Minute Hand", category: "Boost · Riven Hourglass", tier: 1, known: true, readied: false, actionCost: "swift", description: "Make one melee attack as a swift action with a −2 attack penalty.", effects: [{ kind: "modifier", target: "attack.melee", value: -2, bonusType: "penalty", appliesWhen: { maneuvers: ["minute-hand"] } }], roll: { kind: "weaponAttack", attackId: "izanamis-nodachi" } },
      { id: "charlie-maneuver-disturbing-blow", name: "Disturbing Blow", category: "Strike · Veiled Moon", actionCost: "standard", tier: 1, known: true, readied: false, description: "On a hit, impose a −4 penalty on the target's next d20 roll.", roll: { kind: "weaponAttack", attackId: "izanamis-nodachi" } },
      { id: "charlie-maneuver-dizzying-venom-prana", name: "Dizzying Venom Prana", category: "Boost · Steel Serpent", actionCost: "swift", tier: 1, known: true, readied: false, description: "Your next attack inflicts 2 points of Wisdom damage and staggers the target." },
      { id: "charlie-maneuver-mockery", name: "Mockery", category: "Strike · Cursed Razor", actionCost: "standard", tier: 2, known: true, readied: false, description: "Deal +1d6 damage, or +3d6 against a cursed target.", roll: { kind: "weaponAttack", attackId: "izanamis-nodachi", bonusDamage: { count: 1, sides: 6 }, bonusDamageVsCursed: { count: 3, sides: 6 } } },
      { id: "charlie-maneuver-rapid-strike", name: "Rapid Strike", category: "Strike · Riven Hourglass", tier: 2, known: true, readied: false, actionCost: "standard", description: "Make two attacks as a standard action.", roll: { kind: "weaponAttack", attackId: "izanamis-nodachi", repeatCount: 2 } },
    ],
  }, {
    id: "charlie-rajah-veilweaving",
    kind: "veilweaving",
    name: "Rajah Veilweaving",
    progressionId: "pf1e.3pp.akashic.rajah",
    keyAbility: "int",
    resourceName: "Essence",
    resourceSpent: 0,
    essenceCapacityBonus: 1,
    progression: [],
    entries: [
      { id: "charlie-dimensional-bridge", name: "Dimensional Bridge", chakra: "wrists", essenceInvested: 1, known: true, prepared: true, description: "Workbook: 1 essence invested, bound; Focused Veil applies to this veil." },
      { id: "charlie-izanamis-nodachi-veil", name: "Izanami's Nodachi", chakra: "body", essenceInvested: 2, known: true, prepared: false, description: "Workbook: 2 essence invested, shaped and unbound." },
    ],
  }],
  inventory: { gold: 3000 },
  equipment: [],
  damageTaken: 0,
  temporaryHp: 0,
};
