import type { CharacterInput } from "@threepointpf/rules-schema";

/** Core sheet data transcribed from Main Sheet in the supplied Autosheet. */
export const charlieCharacter: CharacterInput = {
  id: "sample-charlie-runecarved-human",
  campaignId: "demo-campaign",
  name: "Charlie",
  baseAbilities: { str: 10, dex: 16, con: 18, int: 26, wis: 10, cha: 10 },
  // Three maximum d8 hit dice plus Constitution gives the workbook's 36 HP.
  baseHpBeforeConstitution: 24,
  baseLandSpeed: 30,
  baseSpeeds: { land: 30, fly: 0, swim: 0, climb: 0, burrow: 0 },
  baseSize: "medium",
  advancementSlots: [1, 2, 3].map((level) => ({
    id: `charlie-level-${level}`,
    tracks: [
      { id: "charlie-rajah", entry: { progressionId: "pf1e.3pp.akashic.rajah" } },
      { id: "charlie-stalker", entry: { progressionId: "pf1e.dreamscarred-press.path-of-war.stalker" } },
    ],
  })),
  skillRanks: {
    acrobatics: 3,
    bluff: 3,
    diplomacy: 3,
    disguise: 3,
    "escape-artist": 3,
    intimidate: 3,
    "knowledge-arcana": 3,
    "knowledge-local": 3,
    "knowledge-nature": 3,
    "knowledge-religion": 3,
    perception: 3,
    spellcraft: 3,
    stealth: 3,
    swim: 3,
    // The workbook's separate Background Skills section.
    appraise: 3,
    linguistics: 3,
  },
  attacks: [
    {
      id: "izanamis-nodachi",
      name: "Izanami's Nodachi",
      attackAbility: "int",
      damageAbility: "int",
      baseDamage: { count: 1, sides: 10 },
      attackTags: ["weapon.melee", "weapon.two-handed"],
      mode: "melee",
      criticalRange: { minimumNaturalRoll: 18 },
      criticalMultiplier: 2,
    },
    {
      id: "izanamis-nodachi-soulburn",
      name: "Izanami's Nodachi (Soulburn)",
      attackAbility: "int",
      damageAbility: "int",
      baseDamage: { count: 1, sides: 10 },
      attackTags: ["weapon.melee", "weapon.two-handed"],
      mode: "melee",
      criticalRange: { minimumNaturalRoll: 18 },
      criticalMultiplier: 2,
    },
  ],
  features: [
    {
      id: "charlie-prescient-dodger",
      name: "Prescient Dodger",
      description: "Stalker art; the workbook records a +8 dodge bonus to AC.",
      enabled: true,
      effects: [{ kind: "modifier", target: "ac", value: 8, bonusType: "dodge", appliesTo: ["normal", "touch", "flatFooted"] }],
    },
    {
      id: "charlie-nodachi-veil",
      name: "Izanami's Nodachi · Veil",
      description: "The workbook lists 2d4+1 bleed damage on this attack.",
      enabled: true,
      effects: [
        {
          kind: "modifier",
          target: "damage.melee",
          value: 1,
          bonusType: "untyped",
          damageType: "bleed",
          appliesWhen: { attackIds: ["izanamis-nodachi", "izanamis-nodachi-soulburn"] },
        },
        {
          kind: "damageDice",
          target: "damage.melee",
          dice: { count: 2, sides: 4 },
          damageType: "bleed",
          label: "Nodachi bleed",
          criticalBehavior: "notMultiplied",
          appliesWhen: { attackIds: ["izanamis-nodachi", "izanamis-nodachi-soulburn"] },
        },
      ],
    },
    {
      id: "charlie-soulburning",
      name: "Soulburning (Su)",
      description: "Optional +1d6 Soulburn damage from the workbook's Soulburn attack entry.",
      enabled: true,
      effects: [{
        kind: "damageDice",
        target: "damage.melee",
        dice: { count: 1, sides: 6 },
        damageType: "soulburn",
        label: "Soulburn",
        criticalBehavior: "normal",
        appliesWhen: { attackIds: ["izanamis-nodachi-soulburn"] },
      }],
    },
    {
      id: "charlie-sheet-notes",
      name: "Workbook details",
      description: "Runecarved Human, neutral; Traits: Bruising Intellect and Unorthodox Method (Broken Blade → Black Seraph). Feats: Extra Origin Feat (Uncanny Aptitude—Nodachi), Focused Veil (Dimensional Bridge), Hidden Brandweaver, and Extra Readied Maneuver. The workbook also lists Shape Veil (Izanami's Nodachi), Soul Claiming, Daayan Veilweaving, Path of the Vazputrika, Ruler's Domain, Actions of a Ruler, Strings of the Sun King, Branded Vassal, Empowered Brands, Oppressing Presence, Tyrant's Grasp, Disguise Self, Invisibility, and Dimensional Bridge (1 essence). These unsupported features are notes; their mechanics are not inferred.",
      enabled: true,
      effects: [],
    },
  ],
  resources: [{
    id: "charlie-ki-pool",
    name: "Ki Pool",
    maximum: { kind: "manual", value: 11 },
    refresh: { kind: "rest" },
  }],
  resourceStates: [{ resourceId: "charlie-ki-pool", spent: 0 }],
  equipment: [],
  damageTaken: 0,
  temporaryHp: 0,
};
